# Enable background transparency
background_opacity 0.5

# Optional: no window decorations (optional for Hyprland)
decorations none
decoration {
    rounding = 8
    blur: 5
    blur-background = true
}
